### PR TITLE
fix: update the read paths for changelogs

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

### CODE REVIEW

**Comment by tsortwehttam** [comment]
LGTM.

**Comment by stristr** [comment]
This is probably not going to work with ASAR.

**Comment by tsortwehttam** [comment]
Is it worth trying or should I just flag it to `asarUnpack` it?

**Comment by roperzh** [comment]
@stristr do you know what we can do? current prod builds can't find the `changelogs/public/` folder

**Comment by stristr** [comment]
Might be worth trying…`packages/haiku-serialization` and `node_modules/haiku-serialization` are at the same level.

Really the best thing to do would have been to make `haiku-changelog` a package, which we should backlog anyway. Then you could just `require.resolve()` and everything would work.

Let's give it a go.

**Pull request merged**
