### PR TITLE
Stage zooming

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Summary of changes:

- Hook up pinch to zoom in Glass ([task](https://app.asana.com/0/743996399535511/755630850610782)).
- Hook up `cmd + 0` on the top menu ([task](https://app.asana.com/0/743996399535511/754154642639650)).

Regressions to look for:

- Not aware of any, but pinch to zoom is behind a flag, just in case.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [x] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Comment by stristr** [comment]
LGTM, except I think the pinch is backward…pinching outward should be zoom in, pinching inward should be zoom out. (cf. Sketch, or Timeline below). Fixed by inverting condition on `wheelEvent.deltaY` sign.

**Comment by roperzh** [comment]
You are totally right, the worst part is that I debated myself for a couple of minutes about this, and strongly decided that this was right 🤦‍♂️.

Fix pushed, thanks!

**Comment by stristr** [comment]
Next time ask the UX department! 😉

**Comment by stristr** [comment]
LGTM, to merge after health checks pass.

**Comment by roperzh** [comment]
lol! thanks for the review

**Pull request merged**
