### PR TITLE
fix: update special casing of single segments dragging for left keyframes

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Summary of changes:

A fix for an 'edge' case that I didn't contemplate in #663 : with this we allow the curve to be resized from both frames.

I also included a test for `Keyframe.groupIsSingleTween`

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Comment by stristr** [comment]
@roperzh, looks like tests are hung. Trying recheck….

**Comment by stristr** [comment]
RECHECK!

**Comment by stristr** [comment]
Oh, it looks like tests are in fact hung.

(You don't need `t.plan(...)` if you have `t.end()`, and in this case, `t.plan(...)` with the wrong number of assertions in the test is the problem.)

**Comment by roperzh** [comment]
thank you very much :)

**Comment by stristr** [comment]
LGTM, merging.

**Pull request merged**
