### PR TITLE
fix: replace CheckTutorial fixtures for Percy

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Changes in this PR:

- [x] Deleted all fixtures related to CheckTutorial
- [x] Added a fixture for Percy using the latest player version at this time (`2.3.78`)

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [ ] Ran the automated tests and linted the code
- [ ] Wrote an automated test covering new functionality

### CODE REVIEW

**Comment by tsortwehttam** [comment]
As discussed with @roperzh (and leaving here for posterity) the health check failure is because the percy code.js content was produced with a version of Haiku that had the bug that I have addressed with #217. This will need to be re-gen'd or manually fixed.

**Comment by roperzh** [comment]
Adding the WIP label until I fix this.

**Comment by roperzh** [comment]
Bytecode updated, this should be ready to go :shipit:

**Comment by stristr** [comment]
LGTM

**Pull request merged**
