### PR TITLE
feat: multiple timeline features

### PR DESCRIPTION
**Pull request by roperzh**
Not OK to merge yet.

Short review.

Summary of changes:

A lot of changes in this PR (sorry about that) but all of them very carefully hidden behind feature flags (@stristr will be happy!).

There's still some work to be done, please hold a couple of hours until it's ready to be reviewed/tested, but it is almost there.

- Timeline marquee selection
- When selecting element on stage, *nicely* scroll to the corresponding row in the timeline?
- Special-casing + disabling `bool` and `string` tweens
- Perf: Horizontal scrolling + timeline-frame-range
- Perf: Smoothness of ticker playback
- General refactors of the timeline CSS

Regressions to look for:

- Timeline in general

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
Note: I get this toast when I pop open `metapoem2`: https://cl.ly/0C2c0q0t1z1Q

Presumably this comes from `this.props.timeline.on('update', this.handleUpdate)` x (number of `TransitionBody` + `SoloKeyframe` + existing subscribers), which dovetails with the scrolling perf improvement to get us to > 500 listeners.

Check `BaseModel#registerUpdateReceiver` for a possibly better way to handle this with a similar event pipe. But…not saying this is easy, but is it possible for the marquee to find the keyframes inside it  and tell them to select instead of having all keyframes check if the marquee is around them all the time?

**Comment by stristr** [comment]
([URL to fork metapoem2](https://share.haiku.ai/u/taylor/metapoem2/fork), if you don't have it handy.)

**Comment by stristr** [comment]
Hey @roperzh, sorry for new conflicts in `experiments.json`. I will fix!

**Comment by stristr** [comment]
(fixed)

**Comment by roperzh** [comment]
Thank you! :)

**Comment by roperzh** [comment]
RECHECK!

**Comment by roperzh** [comment]
RECHECK!

**Pull request closed without merging**
