### PR TITLE
chore: update QA list

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Summary of changes:

Added few QA items that I think are important.

### CODE REVIEW

**Comment by stristr** [comment]
LGTM. Please hold merge until after the release is out (I think there's a vague possibility of merging at the exact wrong time, causing issues with the release, although I haven't really tested this theory).

**Comment by roperzh** [comment]
kk thanks! adding the `hold` label

**Comment by roperzh** [comment]
nvm, you beat me!

**Comment by stristr** [comment]
lol

Also my theory is more of an irrational fear, but just in case.

**Comment by stristr** [comment]
Merging.

**Pull request merged**
