### PR TITLE
Retire disabled experiments

### PR DESCRIPTION
**Pull request by stristr**
HOLD for merge.

Medium review.

Summary of changes:

- Retire experiments that were never disabled in prod.

Regressions to look for:

- Light QA should be done around each disabled experiment to ensure they were successfully disabled. Please hold review/QA until after we release 4.3.1.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality

### CODE REVIEW

**Comment by stristr** [comment]
Ready for review @roperzh!

**Review by roperzh — COMMENTED** [review]
It's awesome to see so much code gone 😅 

LGTM except of a couple of checks for `GlassControlPointShadows` in `packages/haiku-glass/src/react/Glass.js` (which is removed), once they are gone the rest works perfect.

**Comment by stristr** [comment]
Thanks for the check—don't know how I missed that.

Done now.

**Review by roperzh — APPROVED** [review]
LGTM!

**Pull request merged**
