### PR TITLE
RC-3.4.3

### PR DESCRIPTION
**Pull request by tsortwehttam**
WIP, not to merge.

Hot-fix-related code only.

### CODE REVIEW

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by stristr** [comment]
RECHECK!

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
LGTM, merging.

**Pull request merged**
