### PR TITLE
Timeline Fixes (mostly keyframe related)

### PR DESCRIPTION
**Pull request by tsortwehttam**
OK to merge.

Medium review.

Asana task links:

- https://app.asana.com/0/481696547044295/521957330989292
- https://app.asana.com/0/481696547044295/519080338804549
- https://app.asana.com/0/481696547044295/519080338804548

Changes in this PR:

- [x] Fix error when adding curve to generated zeroth keyframe
- [x] Fix deselection when right-clicking element
- [x] Fix problem where deleted keyframe values are still shown
- [x] Fix extraneous issue I discovered with player value interpolation when types mismatch
- [x] Clean up some cruft in Keyframe model

Still todo:

- [x] Review minor changes to selection logic with @taylorpoe to determine if correct
- [x] Have teammate QA to verify it works with mouse (I only have a MBP trackpad)

Notes for the reviewer:

- Wait until I give the OK before reviewing this; there may still be some changes to come

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [x] Ran the automated tests and linted the code
- [x] Wrote an automated test covering new functionality

### CODE REVIEW

**Comment by roperzh** [comment]
✋ I can help with the mouse testing, just let me know

**Comment by roperzh** [comment]
Roberto's QA notes (using mouse):

- _When I drag the keyframe at frame 0 a newly keyframe is created at frame 0_: this works, but the keyframe gets deselected, personally, I expect the keyframe to remain selected because that's how it works in other scenarios:



- _keyframes dragged from zero_: works in most cases, but I'm seeing some weirdness steps:
  - Drag a keyframe from zero
  - Remove that keyframe
  - Drag another keyframe from zero
  - Notice that the keyframe doesn't seems to be being dragged, and there are issues when selecting constant segments

2018-01-16-15_13_43-compressor

- _If I select two keyframes that belong to a tween, the tween is selected too_: This doesn't work, but maybe it's better this way? just wanted to raise for awareness.



- Related to the item above, If I multi-select tweens, and then I deselect a tween, the bounding keyframes remain selected (not saying it's wrong, just noting it)

**Comment by tsortwehttam** [comment]
Awesome notes. I have a couple of these fixed locally already. Will push another update soon.

**Comment by tsortwehttam** [comment]
I think I am code complete on this, but blocked on E2E testing since there appears to be an (unrelated) severe issue with instantiating on stage.

**Comment by tsortwehttam** [comment]
@roperzh when you have a moment can you review this with your mouse again?

(Especially check things related to right click / context menu with your mouse.)

The first two issues you mentioned should be fixed and I am going to circle back separately on the latter two.

**Comment by roperzh** [comment]
**Roberto's QA Notes II**

1. I'm experiencing issues when clicking the last frame of a tween, I can't find consistent repro steps, but it happens really frequently if I click around. Please note that in the following gif I'm not pressing the any key on the keyboard, just using the mouse:

2018-01-18-13_15_01-compressor

2. When multiselecting tweens, some keyframes remain selected when they shouldn't, this is consistent. I included an indicator on the gif so you can see when I'm pressing the shift key

2018-01-18-13_21_21-compressor

**Comment by tsortwehttam** [comment]
OK, I think I know what is causing those. I might circle back and fix these after merging this PR, since these are relatively minor compared to the issues fixed.

**Comment by roperzh** [comment]
Code LGTM.

**Comment by tsortwehttam** [comment]
Merging. Will circle back later today on those last bits Roberto noticed.

**Pull request merged**
