### PR TITLE
Locking

### PR DESCRIPTION
**Pull request by ghost**
OK to merge.

Manual locking and unlocking of layers.

Summary of changes:

- Added lock icon to layers in the timeline
- Locked status stored in bytecode template attribute 'haiku-locked'
- Deselection of selected and directly-selected elements when lock is enabled
- Prevented interaction with timeline property values and keyframes when a layer is locked
- Renamed status for when source design syncing is disabled to prevent confusion

Regressions to look for:

- Interaction issues in the timeline and glass.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [x] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Review by roperzh — COMMENTED** [review]
Code LGTM

**Review by tsortwehttam — DISMISSED** [review]
Only one change I'd like to see: Let's track the layer-lock action in Mixpanel. There should be other examples in haiku-timeline for you to model it after. This is the place you would put it:

https://github.com/HaikuTeam/mono/pull/603/files#diff-49750dcb948eb28243e922aa3c1e20d8R71

**Comment by stristr** [comment]
Couple of observations from test drive:
 - Marquee selection can't be initiated over a locked element. I thought that felt a little bit weird.
 - It looks like `haiku-locked` isn't written to disk, which means the setting won't persist between sessions. Wasn't sure if this was intentional or not; seems like it would persist. If unintentional, check `Template.manaWithOnlyStandardProps`.
 - When I initiate a drag from a locked layer, snapping lines randomly appear. https://cl.ly/3U3p471U2T0T

**Comment by ghost** [comment]
@stristr Nice catches. I pushed a fix for the snapping and marquee issues, but I'm seeing `haiku-locked` written to disk on my end. By adding it to `TEMPLATE_METADATA_ATTRIBUTES` (https://github.com/HaikuTeam/mono/pull/603/files#diff-241b1b80ae81a9960f84d3e3a7f24319R47) I'm seeing it in both the code view within the app and in the bytecode on disk, which is correctly loaded into state when I reopen the project.

screen shot 2018-07-13 at 11 30 31 am

**Comment by stristr** [comment]
My bad! I had checked out an old copy of your branch, and agree this is now fixed. #collabishard. LGTM, let's merge.

**Pull request merged**
