### PR TITLE
Add GNU/Linux dependencies to README.md

### PR DESCRIPTION
**Pull request by partytax**
Summary of changes:

- Copied instructions from 'Mac OS Dependencies to 'Linux OS Dependencies' section, then determined which Debian GNU/Linux dependencies were required to build and run Haiku Animator. Made a simple animation and exported it to GIF to ensure software was working properly.

Regressions to look for:

- None (this is just an update to README.md)

Completed checkin tasks:

- [x] Updated `changelog/public/latest.json`.

### CODE REVIEW

**Comment by mattelen** [comment]
I used these instructions to get it going on my system, and it worked perfectly. Thanks @partytax!

**Comment by partytax** [comment]
@mattelen Glad to hear it! What distro are you running?

**Comment by mattelen** [comment]
Ubuntu 20.04.3 LTS

**Comment by zackbrown** [comment]
Thanks for this, @partytax !  LGTM.

**Pull request merged**
