### PR TITLE
DO NOT MERGE: modify invite endpoints

### PR DESCRIPTION
**Pull request by roperzh**
🔍 Super fast review
🎫 [Task](https://app.asana.com/0/482906470227387/480796620059192)

This updates the invite endpoints on `sdk-inkstone` to match the work done in https://github.com/HaikuTeam/inkstone/pull/22

### CODE REVIEW

**Comment by stristr** [comment]
LGTM, but please see change request in [Inkstone #22](https://github.com/HaikuTeam/inkstone/pull/22#pullrequestreview-88648694) re: breaking API changes.

**Comment by stristr** [comment]
As discussed in [Inkstone #22](https://github.com/HaikuTeam/inkstone/pull/22#pullrequestreview-88648694), I will be taking this over 👍

**Comment by roperzh** [comment]
I'd vote to close this and https://github.com/HaikuTeam/inkstone/pull/22 for clarity, they aren't going to be merged in any case, and if we need them for some reason we can open again.

**Comment by stristr** [comment]
Replaced with #207. @roperzh, sorry to keep the old PRs hanging around! Just wanted to use this as a reference.

**Pull request closed without merging**
