### PR TITLE
fix: use pre-compiled templates in Vue adapter

### PR DESCRIPTION
**Pull request by stristr**
Summary of changes:

- Fixes Vue adapter when used in the context of runtime-only mode. My bad—fixes breaking change when I deployed account just now.

Completed checkin tasks:

- [x] Updated `changelog/public/latest.json`.

### CODE REVIEW

**Comment by roperzh** [comment]
LGTM, sorry for not catching that, it looked better :(

Should we do a new release with this?

**Comment by stristr** [comment]
I don't see any need to break the release cadence…don't think this feature is highly used at the moment.

**Comment by stristr** [comment]
One bug report and I might change my mind :smile:

But I think it can wait.

**Comment by roperzh** [comment]
sounds good!

**Pull request merged**
