### PR TITLE
Timeline ui fixes aug 21

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Summary of changes:

- [Dark/light timeline bg is "moved" ](https://app.asana.com/0/777535458715338/788339780938812)
- [Can't click to select keyframe](https://app.asana.com/0/777535458715338/788339780938818)
- [Zindex organization doesn't scroll the timeline](https://app.asana.com/0/777535458715338/788339780938817)
- [In preview mode the play/pause/loop buttons are active but not working](https://app.asana.com/0/777535458715338/788339780938822)

Another PR with marquee fixes forthcoming.

Regressions to look for:

- Not aware of any

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Comment by stristr** [comment]
I didn't notice "In preview mode the play/pause/loop buttons are active but not working" fixed in this branch. Missing a commit?

**Comment by roperzh** [comment]
🤦‍♂️ I pushed it to the wrong branch, apologies and thanks for noticing that

**Comment by roperzh** [comment]
(commit pushed now)

**Comment by stristr** [comment]
LGTM.

**Comment by stristr** [comment]
…merging.

**Pull request merged**
