### PR TITLE
RC 3.3.0

### PR DESCRIPTION
**Pull request by stristr**
- [Build.](https://ci.haiku.ai/job/HaikuRelease/lastSuccessfulBuild/artifact/dist/Haiku-3.3.0.dmg)
 - [QA checklist.](https://haiku.quip.com/YJmxAiwvyIns)

### CODE REVIEW

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Pull request merged**
