### PR TITLE
Undo/redo create component

### PR DESCRIPTION
**Pull request by stristr**
OK to merge.

Short review.

Summary of changes:

- Adds the ability to undo/redo component creation, including on-disk cleanup.

Regressions to look for:

- None expected, many potentially possible.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Updated `changelog/public/latest.json`

### CODE REVIEW

**Comment by roperzh** [comment]
This works incredible!! a note from early testing, which I think it's a blocker: once the component is gone, the library is not updated, you are able to see the component and "instantiate" it (it instantiates a blank component)

**Comment by stristr** [comment]
Ah, thank you. I forgot to look there. Will try something…

**Comment by stristr** [comment]
…and fix pushed.

**Comment by stristr** [comment]
@roperzh—can you confirm the issue is fixed? Any other findings from QA?

**Comment by roperzh** [comment]
Sorry I forgot to check again! I will do in a moment.

**Review by roperzh — APPROVED** [review]
LGTM

**Pull request merged**
