### PR TITLE
WIP: multi-keyframe, multi-segment actions

### PR DESCRIPTION
**Pull request by taylorpoe**
Please do not merge yet. There are some edge cases I need to take care of with multi-drag and multi-delete.

Please do give feedback if anything here is looking like a bad direction.

Adds:
* multi-keyframe select via shift + click
* keyframe delete via delete key
* multi- keyframe delete via delete key
* multi-keyframe move (drag) https://cl.ly/3j1F2C260l2H
* change multiple segments (both constant and transition) at once https://cl.ly/412F2f0a432l
* Remove tweens from multiple transition segs at once

### CODE REVIEW

**Comment by taylorpoe** [comment]
@matthewtoast This multi-select stuff is all working now other than the bug I introduced with it where keyframes don't stop when they bump another keyframe. Due to us having another trello ticket for handling keyframe bumping, I'm thinking this bug solve belongs with that set of changes (it's on my current list as well). https://trello.com/c/w3QxNA18/476-unable-to-drag-keyframe-segment-from-frame-1-to-0-or-into-another-segment-for-that-matter. And so this PR is probably merge-able unless you'd want to see that next card implemented on this branch first (in order to merge without bugs).

**Comment by tsortwehttam** [comment]
@taylorpoe I'm feeling like we should wait until all of it's together - since it's a pretty significant feature and we'll likely not want to have to re-test/QA back from the beginning again once this fix comes in.

**Comment by tsortwehttam** [comment]
@taylorpoe Just a heads-up that I merged master into this branch ^^ just to get ahead of possible conflicts when the work is done. I did a quick test on this and things seem to be working.

**Comment by taylorpoe** [comment]
Okay cool, thanks for doing that.

**Comment by tsortwehttam** [comment]
Handling this merge myself locally.

**Pull request closed without merging**
