### PR TITLE
Timeline fixes sept5

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Summary of changes:

- Fixes ["Marquee selection doesn't work at some zoom levels"](https://app.asana.com/0/792819786955677/801712328420413)
- ~Fixes ["Reordering elements in timeline doesn't work when row is expanded"](https://app.asana.com/0/792819786955677/801712328420397) by collapsing the row before the drag starts~ not anymore, see comment below

- Disables interaction of the main row with draggable elements, preventing this kind of clunky behavior:

Regressions to look for:

- DnD UX in the timeline

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)
- [x] Updated `changelog/public/latest.json`

### CODE REVIEW

**Review by stristr — DISMISSED** [review]
I tested this and hit the following issue:
 - Instantiate two slices
 - Expand both slices in timeline
 - Scroll to bottom
 - Try to drag bottom slice above top slice

I think this is because by being scrolled to the bottom of the screen, the collapsing jumps the mouse so that I lose the target of the original click-and-hold for the drag action. (If you can't repro this with steps provided, try reducing the vertical height of the timeline.)

**Comment by roperzh** [comment]
Thanks for testing! 🤗 I will take a look

**Comment by roperzh** [comment]
The problem of collapsing a row before dragging turned out to be more complicated than expected, I left a lengthy comment in Asana explaining why and I dropped the commit with the bug from this branch so we can merge the other fixes in the meantime, therefore this is good for another review.

**Comment by roperzh** [comment]
Update: this also fixes https://app.asana.com/0/792819786955677/810915263546987

**Comment by tsortwehttam** [comment]
LGTM, merging.

I did make note of one issue when reviewing @stristr's steps which I've filed here: https://app.asana.com/0/813447917062242/813447917062247

**Pull request merged**
