### PR TITLE
Make monaco autocompleter account for '.' as part word.(797217885228989)

### PR DESCRIPTION
**Pull request by jonaias**
OK to merge.

Monaco editor didn't account for '.' when replacing content with autocomplete selected option: https://github.com/Microsoft/monaco-editor/blob/3a22d5d/monaco.d.ts#L4384. So this PR simulates a word as defined in the regex.  

Additionally 
- Now we also use insert text to complete, so `this.getDef`, can suggest `this.getDefaultTimeline().start()`
- Removed `haiku-glass/src/react/AutoCompleter.js`, afik unused on glass;

- [x] Did manual testing of interrelated functionality
- [x] Updated `changelog/public/latest.json`

### CODE REVIEW

**Review by roperzh — DISMISSED** [review]
Code LGTM and functionality is very nice!

One request, seems like the styling of the auto-complete items is broken on mac:

screen shot 2018-08-29 at 3 44 31 pm

If this looks ok to you in linux let me know and I can take care

**Comment by jonaias** [comment]
Hey Roberto, it is also like that before this PR... Probably a regression.. don't worry I can bisect it! Thanks for reviewing thou.

**Comment by roperzh** [comment]
Great! sorry seems like I missed the `wip` tag

**Comment by jonaias** [comment]
Git bisect + DOM breakpoint saved my life ahhahahah

**Comment by roperzh** [comment]
Ah, so I broke this, sorry @jonaias !

**Pull request merged**
