### PR TITLE
chore: use const enum for the color Palette

### PR DESCRIPTION
**Pull request by roperzh**
OK to merge.

Short review.

Purpose of changes:

This was suggested by @stristr a [long time ago](https://github.com/HaikuTeam/mono/pull/136/files/6df07a2196762172608e469e200d111f1cff5145#r156742748) as will likely come with a minor performance enhancement.

Summary of work (include Asana links if any):

- [x] Use `const enum` for the color palette

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Ran `$ yarn lint-all` and fixed all formatting issues
- [ ] Ran `$ yarn test-all` and all tests passed
- [ ] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [ ] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [ ] Wrote an automated test covering new functionality

### CODE REVIEW

**Comment by roperzh** [comment]
I realized that we can't do this _yet_ as not everything is in TypeScript 🤦‍♂️, my apologies.

**Comment by tsortwehttam** [comment]
Wait, can't we require the _compiled_ module from non-typescript modules?

**Comment by roperzh** [comment]
AFAIK, we can't, this was replacing variables for strings at compile time directly in the code and exporting an empty module as `Palette`, so for example, if the source code was:

```js
const myColor = Palette.BLUE
```

the compiled output was:

```js
const myColor = '#4A90E2'
```

**Comment by stristr** [comment]
Yeah, sorry about that! We need TypeScript for all first.

**Pull request closed without merging**
