### PR TITLE
Code snippet insertion button outside monaco (759100037963950)

### PR DESCRIPTION
**Pull request by jonaias**
OK to merge after @taylorpoe green light.

@taylorpoe, do you have any input on design side?

peek 2018-08-23 13-08

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality

### CODE REVIEW

**Comment by stristr** [comment]
I believe the suggestion in the ticket was to keep it inline, but add a gutter on the right side of the monaco textarea where it sits. Is that feasible?

**Comment by taylorpoe** [comment]
I'm not a fan of having this outside of the visible editor. I think to solve the code overlap we should do this.

**Comment by taylorpoe** [comment]
image

**Comment by jonaias** [comment]
@stristr , I've miss-interpreted the asana description, my bad.

Following @taylorpoe  guidelines:

peek 2018-08-23 14-35

**Comment by stristr** [comment]
So…does this solve the issue where I can't see what I'm typing when my cursor is at the end of the line?

It looks like maybe it doesn't, because text is still allowed to flow all the way to the end of the box. Is that right?

**Comment by jonaias** [comment]
Atm is working like vscode. If you scroll to left on a really long line, the cursor will disappear on right, but as soon as you type any keystroke (including arrow keys) the current line position is made visible automatically by monaco. The '+' button to text overlap is gone.

What I think that might help is to make the width of text area smaller (Exactly 30 pixels, the width of the added div). Go for it?

**Comment by stristr** [comment]
No; this is perfect as is (just tried it). I think the GIF just didn't do it justice :smile:

LGTM, merging.

**Pull request merged**
