### PR TITLE
Fixed code editor indentation.

### PR DESCRIPTION
**Pull request by ghost**
OK to merge.

Fixed [indentation guides](https://app.asana.com/0/706302920652186/754815165094590) by waiting for font to be loaded before mounting Monaco. See [here](https://github.com/Microsoft/monaco-editor/issues/836). Even though the font is specified in CSS, it's not actually loaded until used, so `document.fonts.load` forces it.

**Before:**
screen shot 2018-07-24 at 11 01 51 am

**After:**
screen shot 2018-07-24 at 11 00 31 am

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [ ] Wrote an automated test for existing and modified functionality
- [ ] Added measurement instrumentation (Mixpanel, etc.)

### CODE REVIEW

**Comment by stristr** [comment]
LGTM, okay to merge after health checks pass.

Nice catch and fix.

**Comment by stristr** [comment]
Lint errors unreleated to this PR, so merging.

(Helpful to rebase with `git fetch && git rebase origin/master` before pushing PRs.)

**Comment by roperzh** [comment]
@winduptoy you rock! I have no idea how you connected that two dots.

**Comment by stristr** [comment]
I'm guessing it's either Google or magic.

**Comment by ghost** [comment]
@roperzh This one was easy. Figuring out why there's a newline inserted when pressing space in the code editor is about to kill me. :rage4:

**Pull request merged**
