### PR TITLE
RC-3.4.0

### PR DESCRIPTION
**Pull request by tsortwehttam**

### CODE REVIEW

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME! up, Scotty!

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
BUILDME!

**Comment by stristr** [comment]
LGTM, merging.

**Pull request merged**
