### PR TITLE
Aria Tooltips, Button Titles, and Dash New Project Button

### PR DESCRIPTION
**Pull request by tsortwehttam**
OK to merge.

Short review.

Summary of changes:

- It's been bothering me for months that we don't have a 'New Project' thumbnail to lead off the set of project thumbnails. So I added it.

screen shot 2018-08-21 at 10 52 19 am

- A bunch of buttons/icons in the app didn't have any `title="..."` attribute set, so you wouldn't get the explanatory hover text. I added this text in a bunch of places. Makes UX feel slightly more polished and friendly.

- Made some minor copy tweaks to some labels and help text blocks.

### CODE REVIEW

**Comment by tsortwehttam** [comment]
cc @taylorpoe ^^

**Comment by stristr** [comment]
Honestly, this bothers me: https://cl.ly/2p0U2t1r1x3Z

Could we perhaps do away with the title bar button?

**Comment by taylorpoe** [comment]
The new-proj thumbnail was the original design but we didn't go with it. . The reason I didn't implement it was because it gave me a sniff of amateurishness at one point. I do _not_ hate it though. It needs a bit of love to set it apart.

The title bar redunancy doesn't bother me too much though I wouldn't mind scrapping it. Made a task to sort through these when I get a moment. https://app.asana.com/0/777535458715338/789275054861247

**Comment by stristr** [comment]
@taylorpoe said not planning to give UI love before `4.0.0`, so tagging "hold".

**Comment by taylorpoe** [comment]
I made a task for it. https://app.asana.com/0/777535458715338/789275054861247

Btw I was thinking about it a bit more and I think we need that top [+ New Project] button no matter what because the user can scroll the large “card” new project button out of view if they have 16 + projects.
I believe this was the main factor in not placing the new proj button as a card originally.

Not opposed to keeping the card though. Just want to touch it up a tweak.

**Comment by tsortwehttam** [comment]
Merged @roperzh's #746 into this since it's all related.

**Comment by stristr** [comment]
@taylorpoe LGTY?

**Review by stristr — DISMISSED** [review]
Some changes requested:
 - Let's migrate TooltipStyles.tsx to a regular old CSS file loaded in index.html(s).
 - yarn.lock an extra copy of `balloon-css` in it that should be removed.

Rest LGTM.

**Pull request merged**
