### PR TITLE
Tour updates

### PR DESCRIPTION
**Pull request by roperzh**
~This is almost ready to review, but please hold on reviewing and merging until we do a last check on content and styling with @nadonomy .~

OK to review, ~please let @roperzh do the merge, because we depend on Percy being available as a template project.~

⚠️ There's a document [outlining the instructions to merge](https://haiku.quip.com/k95wAd2nyYau), please note that this needs some coordination with the back-end.

Medium review.

Asana task link: https://app.asana.com/0/482906470227387/519596902790174

Changes in this PR:

- [x] Updated the tour content, [video demo here](https://files.slack.com/files-pri/T13B54H1S-F8T3QKAFK/tour.mov?pub_secret=32498ac5cd)

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality
- [x] Did the [E2E checklist](https://haiku.quip.com/dGqeAEVSWdmg)
- [x] Expanded the [QA checklist](https://haiku.quip.com/rqwsAPsCGxqT)
- [x] Ran the automated tests and linted the code
- [ ] Wrote an automated test covering new functionality

### CODE REVIEW

**Comment by tsortwehttam** [comment]
I noticed there is an error when you publish the project. Any idea what is going on there?

**Comment by stristr** [comment]
@matthewtoast, just checking—it's not a publish error, right? If it is it could be unrelated to these changes.

**Comment by tsortwehttam** [comment]
In the video demo ^^, when the project is published, it says "Oh no!" I was wondering if that error was expected or not?

**Comment by roperzh** [comment]
> I was wondering if that error was expected or not?

Yes, as the error is that eval error you guys fixed the other day, **but** I will rebase master and test again. Thanks for the heads up

**Comment by roperzh** [comment]
Updated main post with a link to a document with the deploy/merge instructions.

**Comment by tsortwehttam** [comment]
Code LGTM. Can we get this guy merged?

**Comment by roperzh** [comment]
> Code LGTM. Can we get this guy merged?

@matthewtoast if we merge this, we need to consider two things:

1. The tour would be disabled on subsequent builds for existing users because the Percy project will not be available.
2. Because of 1, we need to be cautious as soon as this goes live to enable Percy in the default org and disable CheckTutorial.

Besides of that, if you think it's good to go just press the button!

**Comment by tsortwehttam** [comment]
OK, since that will only be an issue when we roll a distro, I'm going to go ahead and merge this.

**Pull request merged**
