### PR TITLE
Upgrade electron

### PR DESCRIPTION
**Pull request by stristr**
OK to merge (after testing BUILDME!)

Short review.

Summary of changes:

- Upgrade Electron.
- Target `ESNext` in TypeScript projects.

Regressions to look for:

- Subtle and potentially app-wide, but I have done some rigorous testing already.

Notes for reviewers:

- I am especially excited about getting this in because it allows us to target `ESNext` in both the renderer processes (Chrome 61) and the main process (Node 8.9.3). Since we use CommonJS module resolution the `ESNext` changes that _don't_ work in our new runtimes really shouldn't be an issue. Theoretically `ESNext` means: 1. faster compilations (less to transpile), and 2. faster runtime due to optimizations around specific new language features + fewer polyfills. Still should be vigorously tested in a proper build.

Completed checkin tasks:

- [x] Did manual testing of interrelated functionality

### CODE REVIEW

**Comment by stristr** [comment]
BUILDME!

**Comment by tsortwehttam** [comment]
Code LGTM.

**Comment by stristr** [comment]
BUILDME!

**Comment by stristr** [comment]
This builds and held up to fairly rigorous manual testing. I'm squash-merging this to `master` so we have a single commit to roll back if we encounter any "weirdness" in production.

**Pull request merged**
